<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $makanan = Category::where('name', 'Makanan')->first();
        $minuman = Category::where('name', 'Minuman')->first();
        $alatTulis = Category::where('name', 'Alat Tulis')->first();
        $kebersihan = Category::where('name', 'Kebersihan')->first();
        $rokok = Category::where('name', 'Rokok')->first();

        $products = [
            // Makanan
            [
                'name' => 'Indomie Goreng',
                'description' => 'Mie instan rasa goreng original',
                'categoryId' => $makanan->id,
                'sku' => 'IND-001',
                'buyPrice' => 2500,
                'sellPrice' => 3000,
                'stock' => 100,
                'threshold' => 20,
                'unit' => 'pcs',
                'ownershipType' => 'TOKO',
                'status' => 'ACTIVE',
                'isConsignment' => false,
                'isActive' => true,
            ],
            [
                'name' => 'Indomie Soto',
                'description' => 'Mie instan rasa soto',
                'categoryId' => $makanan->id,
                'sku' => 'IND-002',
                'buyPrice' => 2500,
                'sellPrice' => 3000,
                'stock' => 80,
                'threshold' => 20,
                'unit' => 'pcs',
                'ownershipType' => 'TOKO',
                'status' => 'ACTIVE',
                'isConsignment' => false,
                'isActive' => true,
            ],
            [
                'name' => 'Chitato Sapi Panggang',
                'description' => 'Keripik kentang rasa sapi panggang',
                'categoryId' => $makanan->id,
                'sku' => 'CHT-001',
                'buyPrice' => 8000,
                'sellPrice' => 10000,
                'stock' => 50,
                'threshold' => 10,
                'unit' => 'pcs',
                'ownershipType' => 'TOKO',
                'status' => 'ACTIVE',
                'isConsignment' => false,
                'isActive' => true,
            ],
            [
                'name' => 'Roti Tawar Sari Roti',
                'description' => 'Roti tawar kemasan',
                'categoryId' => $makanan->id,
                'sku' => 'ROT-001',
                'buyPrice' => 10000,
                'sellPrice' => 12000,
                'stock' => 30,
                'threshold' => 5,
                'unit' => 'pcs',
                'ownershipType' => 'TOKO',
                'status' => 'ACTIVE',
                'isConsignment' => false,
                'isActive' => true,
            ],

            // Minuman
            [
                'name' => 'Aqua 600ml',
                'description' => 'Air mineral kemasan 600ml',
                'categoryId' => $minuman->id,
                'sku' => 'AQU-001',
                'buyPrice' => 2000,
                'sellPrice' => 3000,
                'stock' => 120,
                'threshold' => 30,
                'unit' => 'pcs',
                'ownershipType' => 'TOKO',
                'status' => 'ACTIVE',
                'isConsignment' => false,
                'isActive' => true,
            ],
            [
                'name' => 'Coca Cola 390ml',
                'description' => 'Minuman bersoda cola',
                'categoryId' => $minuman->id,
                'sku' => 'COK-001',
                'buyPrice' => 4000,
                'sellPrice' => 5000,
                'stock' => 60,
                'threshold' => 15,
                'unit' => 'pcs',
                'ownershipType' => 'TOKO',
                'status' => 'ACTIVE',
                'isConsignment' => false,
                'isActive' => true,
            ],
            [
                'name' => 'Teh Pucuk Harum',
                'description' => 'Teh dalam kemasan botol',
                'categoryId' => $minuman->id,
                'sku' => 'TEH-001',
                'buyPrice' => 3500,
                'sellPrice' => 5000,
                'stock' => 80,
                'threshold' => 20,
                'unit' => 'pcs',
                'ownershipType' => 'TOKO',
                'status' => 'ACTIVE',
                'isConsignment' => false,
                'isActive' => true,
            ],
            [
                'name' => 'Susu Ultra Coklat 250ml',
                'description' => 'Susu UHT rasa coklat',
                'categoryId' => $minuman->id,
                'sku' => 'ULT-001',
                'buyPrice' => 5000,
                'sellPrice' => 6500,
                'stock' => 40,
                'threshold' => 10,
                'unit' => 'pcs',
                'ownershipType' => 'TOKO',
                'status' => 'ACTIVE',
                'isConsignment' => false,
                'isActive' => true,
            ],

            // Alat Tulis
            [
                'name' => 'Pulpen Standard AE7',
                'description' => 'Pulpen standar warna biru',
                'categoryId' => $alatTulis->id,
                'sku' => 'PEN-001',
                'buyPrice' => 1500,
                'sellPrice' => 2000,
                'stock' => 100,
                'threshold' => 20,
                'unit' => 'pcs',
                'ownershipType' => 'TOKO',
                'status' => 'ACTIVE',
                'isConsignment' => false,
                'isActive' => true,
            ],
            [
                'name' => 'Buku Tulis Sinar Dunia 58 Lembar',
                'description' => 'Buku tulis folio bergaris',
                'categoryId' => $alatTulis->id,
                'sku' => 'BUK-001',
                'buyPrice' => 3000,
                'sellPrice' => 4000,
                'stock' => 50,
                'threshold' => 10,
                'unit' => 'pcs',
                'ownershipType' => 'TOKO',
                'status' => 'ACTIVE',
                'isConsignment' => false,
                'isActive' => true,
            ],
            [
                'name' => 'Pensil 2B Faber Castell',
                'description' => 'Pensil 2B untuk menulis',
                'categoryId' => $alatTulis->id,
                'sku' => 'PEN-002',
                'buyPrice' => 2000,
                'sellPrice' => 3000,
                'stock' => 80,
                'threshold' => 15,
                'unit' => 'pcs',
                'ownershipType' => 'TOKO',
                'status' => 'ACTIVE',
                'isConsignment' => false,
                'isActive' => true,
            ],

            // Kebersihan
            [
                'name' => 'Sabun Mandi Lifebuoy',
                'description' => 'Sabun mandi batangan',
                'categoryId' => $kebersihan->id,
                'sku' => 'SAB-001',
                'buyPrice' => 2500,
                'sellPrice' => 3500,
                'stock' => 60,
                'threshold' => 15,
                'unit' => 'pcs',
                'ownershipType' => 'TOKO',
                'status' => 'ACTIVE',
                'isConsignment' => false,
                'isActive' => true,
            ],
            [
                'name' => 'Tissue Paseo 250 Sheet',
                'description' => 'Tissue facial',
                'categoryId' => $kebersihan->id,
                'sku' => 'TIS-001',
                'buyPrice' => 8000,
                'sellPrice' => 10000,
                'stock' => 40,
                'threshold' => 10,
                'unit' => 'pcs',
                'ownershipType' => 'TOKO',
                'status' => 'ACTIVE',
                'isConsignment' => false,
                'isActive' => true,
            ],

            // Rokok
            [
                'name' => 'Sampoerna Mild 16',
                'description' => 'Rokok filter mild',
                'categoryId' => $rokok->id,
                'sku' => 'ROK-001',
                'buyPrice' => 25000,
                'sellPrice' => 28000,
                'stock' => 100,
                'threshold' => 20,
                'unit' => 'pack',
                'ownershipType' => 'TOKO',
                'status' => 'ACTIVE',
                'isConsignment' => false,
                'isActive' => true,
            ],
            [
                'name' => 'Djarum Super 12',
                'description' => 'Rokok kretek filter',
                'categoryId' => $rokok->id,
                'sku' => 'ROK-002',
                'buyPrice' => 18000,
                'sellPrice' => 20000,
                'stock' => 80,
                'threshold' => 20,
                'unit' => 'pack',
                'ownershipType' => 'TOKO',
                'status' => 'ACTIVE',
                'isConsignment' => false,
                'isActive' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
