<?php

return [
    'neraca' => [
        'title' => 'Laporan Neraca',
        'columns' => [
            ['key' => 'current', 'label' => 'Mei {year}', 'year_offset' => 0],
            ['key' => 'previous', 'label' => 'Mei {prev}', 'year_offset' => -1],
        ],
        'rows' => [
            ['type' => 'section', 'label' => 'AKTIVA'],
            ['key' => 'kas', 'label' => 'Kas', 'level' => 1],
            [
                'key' => 'penempatan_bank_syariah',
                'label' => 'Penempatan pada Bank/Koperasi Syariah',
                'level' => 1,
                'auto_key' => 'neraca_penempatan_bank_syariah',
            ],
            ['type' => 'group', 'label' => 'Piutang', 'level' => 1],
            ['key' => 'piutang_murabahah', 'label' => '- Murabahah', 'level' => 2],
            ['key' => 'piutang_salam', 'label' => '- Salam', 'level' => 2],
            ['key' => 'piutang_istishna', 'label' => '- Istishna', 'level' => 2],
            ['type' => 'group', 'label' => 'Pembiayaan', 'level' => 1],
            ['key' => 'pembiayaan_mudharabah', 'label' => '- Mudharabah', 'level' => 2],
            ['key' => 'pembiayaan_musyarakah', 'label' => '- Musyarakah', 'level' => 2],
            ['key' => 'pembiayaan_ijarah', 'label' => '- Ijarah', 'level' => 2],
            ['key' => 'pembiayaan_multijasa', 'label' => '- Transaksi Multijasa', 'level' => 2],
            ['key' => 'pinjaman_qardh', 'label' => 'Pinjaman Qardh', 'level' => 1],
            ['key' => 'persediaan', 'label' => 'Persediaan', 'level' => 1],
            ['key' => 'margin_ditangguhkan', 'label' => 'Margin yang ditangguhkan', 'level' => 1],
            ['key' => 'aset_ijarah', 'label' => 'Aset Ijarah', 'level' => 1],
            ['key' => 'aset_istishna_dalam_penyelesaian', 'label' => 'Aset Istishna dalam penyelesaian', 'level' => 1],
            ['key' => 'aktiva_kelolaan_sektor_riil', 'label' => 'Aktiva Kelolaan: Sektor Riil', 'level' => 1],
            ['key' => 'aktiva_tetap_dan_inventaris', 'label' => 'Aktiva Tetap dan Inventaris', 'level' => 1],
            ['key' => 'penyusutan_aktiva_tetap_dan_inventaris', 'label' => 'Penyusutan aktiva Tetap dan Inventaris', 'level' => 1, 'sign' => -1],
            ['key' => 'rupa_rupa_aktiva', 'label' => 'Rupa-rupa Aktiva', 'level' => 1],
            [
                'type' => 'total',
                'key' => 'total_aktiva',
                'label' => 'TOTAL AKTIVA',
                'sum_of' => [
                    'kas',
                    'penempatan_bank_syariah',
                    'piutang_murabahah',
                    'piutang_salam',
                    'piutang_istishna',
                    'pembiayaan_mudharabah',
                    'pembiayaan_musyarakah',
                    'pembiayaan_ijarah',
                    'pembiayaan_multijasa',
                    'pinjaman_qardh',
                    'persediaan',
                    'margin_ditangguhkan',
                    'aset_ijarah',
                    'aset_istishna_dalam_penyelesaian',
                    'aktiva_kelolaan_sektor_riil',
                    'aktiva_tetap_dan_inventaris',
                    'penyusutan_aktiva_tetap_dan_inventaris',
                    'rupa_rupa_aktiva',
                ],
            ],
            ['type' => 'section', 'label' => 'KEWAJIBAN'],
            ['key' => 'kewajiban_segera', 'label' => 'Kewajiban segera', 'level' => 1],
            ['key' => 'bagi_hasil_belum_dibagikan', 'label' => 'Bagi hasil yang belum dibagikan', 'level' => 1],
            [
                'key' => 'simpanan_sukarela_wadiah',
                'label' => 'Simpanan Sukarela Wadiah',
                'level' => 1,
                'auto_key' => 'simpanan_sukarela_balance',
            ],
            ['key' => 'pembiayaan_diterima', 'label' => 'Pembiayaan yang diterima', 'level' => 1],
            ['key' => 'hutang_pajak', 'label' => 'Hutang pajak', 'level' => 1],
            ['key' => 'kewajiban_lainnya', 'label' => 'Kewajiban lainnya', 'level' => 1],
            [
                'type' => 'total',
                'key' => 'jumlah_kewajiban',
                'label' => 'Jumlah Kewajiban',
                'sum_of' => [
                    'kewajiban_segera',
                    'bagi_hasil_belum_dibagikan',
                    'simpanan_sukarela_wadiah',
                    'pembiayaan_diterima',
                    'hutang_pajak',
                    'kewajiban_lainnya',
                ],
            ],
            ['type' => 'section', 'label' => 'DANA SYIRKAH TEMPORER'],
            ['type' => 'group', 'label' => 'Dari Anggota', 'level' => 1],
            ['key' => 'simpanan_berjangka_mudharabah_anggota', 'label' => '- Simpanan Sukarela Berjangka Mudharabah', 'level' => 2],
            ['key' => 'investasi_mudharabah_lainnya_anggota', 'label' => '- Investasi Mudharabah lainnya', 'level' => 2],
            ['type' => 'group', 'label' => 'Dari Non-Anggota', 'level' => 1],
            ['key' => 'simpanan_berjangka_mudharabah_non_anggota', 'label' => '- Simpanan Sukarela Berjangka Mudharabah', 'level' => 2],
            ['key' => 'investasi_mudharabah_lainnya_non_anggota', 'label' => '- Investasi Mudharabah lainnya', 'level' => 2],
            ['key' => 'musyarakah_non_anggota', 'label' => '- Musyarakah', 'level' => 2],
            [
                'type' => 'total',
                'key' => 'jumlah_dana_syirkah_temporer',
                'label' => 'Jumlah Dana Syirkah Temporer',
                'sum_of' => [
                    'simpanan_berjangka_mudharabah_anggota',
                    'investasi_mudharabah_lainnya_anggota',
                    'simpanan_berjangka_mudharabah_non_anggota',
                    'investasi_mudharabah_lainnya_non_anggota',
                    'musyarakah_non_anggota',
                ],
            ],
            ['type' => 'section', 'label' => 'EKUITAS'],
            ['key' => 'simpanan_pokok', 'label' => 'Simpanan Pokok', 'level' => 1, 'auto_key' => 'simpanan_pokok_balance'],
            ['key' => 'simpanan_wajib', 'label' => 'Simpanan Wajib', 'level' => 1, 'auto_key' => 'simpanan_wajib_balance'],
            ['key' => 'cadangan', 'label' => 'Cadangan', 'level' => 1],
            ['key' => 'pendapatan_shu_berjalan', 'label' => 'Pendapatan SHU Berjalan', 'level' => 1],
            [
                'type' => 'total',
                'key' => 'jumlah_ekuitas',
                'label' => 'Jumlah Ekuitas',
                'sum_of' => [
                    'simpanan_pokok',
                    'simpanan_wajib',
                    'cadangan',
                    'pendapatan_shu_berjalan',
                ],
            ],
            [
                'type' => 'total',
                'key' => 'total_kewajiban_dana_syirkah_dan_ekuitas',
                'label' => 'TOTAL KEWAJIBAN DANA SYIRKAH TEMPORER DAN EKUITAS',
                'sum_of' => [
                    'jumlah_kewajiban',
                    'jumlah_dana_syirkah_temporer',
                    'jumlah_ekuitas',
                ],
            ],
        ],
    ],
    'laba_rugi' => [
        'title' => 'Laporan Hasil Usaha (Laba Rugi)',
        'columns' => [
            ['key' => 'current', 'label' => 'Mei {year}', 'year_offset' => 0],
            ['key' => 'previous', 'label' => 'Mei {prev}', 'year_offset' => -1],
        ],
        'rows' => [
            ['type' => 'section', 'label' => 'I. Pendapatan Operasional'],
            ['type' => 'section', 'label' => 'A. Pendapatan dari Penyaluran Dana', 'level' => 1],
            ['type' => 'group', 'label' => 'Dari Penyaluran ke Anggota', 'level' => 2],
            [
                'key' => 'pendapatan_margin',
                'label' => '- Pendapatan Margin',
                'level' => 3,
                'auto_key' => 'laba_rugi_pendapatan_margin',
            ],
            ['key' => 'pendapatan_sewa', 'label' => '- Pendapatan Sewa', 'level' => 3],
            ['key' => 'pendapatan_bagi_hasil', 'label' => '- Pendapatan Bagi Hasil', 'level' => 3],
            ['key' => 'pendapatan_multijasa', 'label' => '- Pendapatan Multijasa', 'level' => 3],
            ['type' => 'group', 'label' => 'Dari Bank-Bank Syariah', 'level' => 2],
            [
                'key' => 'bagi_hasil_tabungan',
                'label' => '- Bagi Hasil Tabungan',
                'level' => 3,
                'auto_key' => 'laba_rugi_bagi_hasil_tabungan',
            ],
            ['key' => 'bagi_hasil_deposito', 'label' => '- Bagi Hasil Deposito', 'level' => 3],
            ['key' => 'bonus_giro', 'label' => '- Bonus Giro', 'level' => 3],
            ['type' => 'section', 'label' => 'B. Pendapatan Operasional Lainnya', 'level' => 1],
            ['key' => 'jasa_investasi_terikat', 'label' => '- Jasa Investasi Terikat', 'level' => 2],
            ['key' => 'jasa_layanan', 'label' => '- Jasa Layanan', 'level' => 2],
            ['key' => 'pendapatan_qardh', 'label' => '- Pendapatan Qardh', 'level' => 2],
            ['key' => 'pendapatan_administrasi', 'label' => '- Pendapatan Administrasi', 'level' => 2],
            [
                'key' => 'pendapatan_lainnya',
                'label' => '- Pendapatan lainnya',
                'level' => 2,
                'auto_key' => 'laba_rugi_pendapatan_lainnya',
            ],
            [
                'type' => 'total',
                'key' => 'total_pendapatan_operasional',
                'label' => 'Total Pendapatan Operasional',
                'sum_of' => [
                    'pendapatan_margin',
                    'pendapatan_sewa',
                    'pendapatan_bagi_hasil',
                    'pendapatan_multijasa',
                    'bagi_hasil_tabungan',
                    'bagi_hasil_deposito',
                    'bonus_giro',
                    'jasa_investasi_terikat',
                    'jasa_layanan',
                    'pendapatan_qardh',
                    'pendapatan_administrasi',
                    'pendapatan_lainnya',
                ],
            ],
            ['type' => 'section', 'label' => 'II. Bagi Hasil Kepada Pemilik Dana'],
            ['type' => 'group', 'label' => 'A. Anggota Koperasi Syariah', 'level' => 1],
            ['key' => 'bagi_hasil_simpanan_berjangka', 'label' => '- Simpanan Berjangka Mudharabah', 'level' => 2],
            ['key' => 'bagi_hasil_investasi_mudharabah', 'label' => '- Investasi Mudharabah', 'level' => 2],
            ['type' => 'group', 'label' => 'B. Non-Anggota Koperasi Syariah', 'level' => 1],
            ['key' => 'bagi_hasil_investasi_terikat', 'label' => '- Bagi hasil investasi terikat', 'level' => 2],
            ['key' => 'bagi_hasil_investasi_tidak_terikat', 'label' => '- Bagi hasil investasi tidak terikat', 'level' => 2],
            [
                'type' => 'total',
                'key' => 'total_bagi_hasil_pemilik_dana',
                'label' => 'Total Bagi Hasil Pemilik Dana',
                'sum_of' => [
                    'bagi_hasil_simpanan_berjangka',
                    'bagi_hasil_investasi_mudharabah',
                    'bagi_hasil_investasi_terikat',
                    'bagi_hasil_investasi_tidak_terikat',
                ],
            ],
            [
                'type' => 'total',
                'key' => 'pendapatan_operasional_setelah_distribusi',
                'label' => 'III. Pendapatan Operasional Setelah Distribusi Bagi Hasil (I - II)',
                'sum_of' => [
                    'total_pendapatan_operasional',
                    ['key' => 'total_bagi_hasil_pemilik_dana', 'sign' => -1],
                ],
            ],
            ['type' => 'section', 'label' => 'IV. Beban Operasional'],
            ['key' => 'beban_bonus_simpanan_wadiah', 'label' => '- Beban Bonus Simpanan Wadiah', 'level' => 1],
            ['key' => 'beban_tenaga_kerja', 'label' => '- Beban tenaga kerja', 'level' => 1],
            ['key' => 'pendidikan_dan_pelatihan', 'label' => '- Pendidikan dan Pelatihan', 'level' => 1],
            ['key' => 'promosi', 'label' => '- Promosi', 'level' => 1],
            [
                'key' => 'pajak_pajak',
                'label' => '- Pajak-Pajak',
                'level' => 1,
                'auto_key' => 'laba_rugi_pajak_pajak',
            ],
            ['key' => 'pembelian_aktiva_tetap_dan_inventaris', 'label' => '- Pembelian Aktiva Tetap dan Inventaris', 'level' => 1],
            ['key' => 'penyusutan_amortisasi', 'label' => '- Penyusutan Penyisihan / Amortisasi', 'level' => 1],
            [
                'key' => 'beban_lainnya',
                'label' => '- Beban Lainnya',
                'level' => 1,
                'auto_key' => 'laba_rugi_beban_lainnya',
            ],
            [
                'type' => 'total',
                'key' => 'total_beban_operasional',
                'label' => 'Total Beban Operasional',
                'sum_of' => [
                    'beban_bonus_simpanan_wadiah',
                    'beban_tenaga_kerja',
                    'pendidikan_dan_pelatihan',
                    'promosi',
                    'pajak_pajak',
                    'pembelian_aktiva_tetap_dan_inventaris',
                    'penyusutan_amortisasi',
                    'beban_lainnya',
                ],
            ],
            [
                'type' => 'total',
                'key' => 'laba_rugi_operasional',
                'label' => 'V. Laba Rugi Operasional (III - IV)',
                'sum_of' => [
                    'pendapatan_operasional_setelah_distribusi',
                    ['key' => 'total_beban_operasional', 'sign' => -1],
                ],
            ],
            ['type' => 'section', 'label' => 'VI. Pendapatan Non Operasional'],
            ['key' => 'hasil_penjualan_aktiva', 'label' => '- Hasil Penjualan Aktiva', 'level' => 1],
            ['key' => 'goodwill', 'label' => '- Goodwill', 'level' => 1],
            [
                'type' => 'total',
                'key' => 'total_pendapatan_non_operasional',
                'label' => 'Total Pendapatan Non Operasional',
                'sum_of' => [
                    'hasil_penjualan_aktiva',
                    'goodwill',
                ],
            ],
            ['type' => 'section', 'label' => 'VII. Beban Non Operasional'],
            ['key' => 'force_majeure', 'label' => '- Force Majeure', 'level' => 1],
            ['key' => 'beban_non_operasional_lainnya', 'label' => '- Lainnya', 'level' => 1],
            [
                'type' => 'total',
                'key' => 'total_beban_non_operasional',
                'label' => 'Total Beban Non Operasional',
                'sum_of' => [
                    'force_majeure',
                    'beban_non_operasional_lainnya',
                ],
            ],
            [
                'type' => 'total',
                'key' => 'laba_rugi_non_operasional',
                'label' => 'VIII. Laba Rugi Non Operasional (VI - VII)',
                'sum_of' => [
                    'total_pendapatan_non_operasional',
                    ['key' => 'total_beban_non_operasional', 'sign' => -1],
                ],
            ],
            [
                'type' => 'total',
                'key' => 'laba_rugi_shu_berjalan',
                'label' => 'IX. Laba Rugi SHU Berjalan (V + VIII)',
                'sum_of' => [
                    'laba_rugi_operasional',
                    'laba_rugi_non_operasional',
                ],
            ],
            ['key' => 'taksiran_pajak_penghasilan', 'label' => 'X. Taksiran Pajak Penghasilan', 'sign' => -1],
            [
                'type' => 'total',
                'key' => 'jumlah_laba_shu_berjalan',
                'label' => 'XI. Jumlah Laba SHU Berjalan',
                'sum_of' => [
                    'laba_rugi_shu_berjalan',
                    'taksiran_pajak_penghasilan',
                ],
            ],
        ],
    ],
    'perubahan_modal' => [
        'title' => 'Laporan Perubahan Modal',
        'columns' => [
            ['key' => 'simp_pokok', 'label' => 'Simp. Pokok', 'field_key' => 'simp_pokok'],
            ['key' => 'simp_wajib', 'label' => 'Simp. Wajib', 'field_key' => 'simp_wajib'],
            ['key' => 'cadangan', 'label' => 'Cadangan', 'field_key' => 'cadangan'],
            ['key' => 'hibah', 'label' => 'Hibah', 'field_key' => 'hibah'],
            ['key' => 'jumlah_modal', 'label' => 'Jumlah Modal', 'field_key' => 'jumlah_modal'],
        ],
        'rows' => [
            ['key' => 'modal_awal_tahun', 'label' => 'Modal Awal Tahun'],
            ['key' => 'penambahan_modal_setoran', 'label' => 'Penambahan Modal Setoran'],
            ['key' => 'modal_pembentukan_cadangan', 'label' => 'Modal Pembentukan Cadangan'],
            ['key' => 'penerimaan_hibah', 'label' => 'Penerimaan Hibah'],
            ['key' => 'saldo_penambahan_modal', 'label' => 'Saldo Penambahan Modal'],
            ['key' => 'pengurangan_modal', 'label' => 'Pengurangan Modal'],
            ['key' => 'pemakaian_cadangan', 'label' => 'Pemakaian Cadangan'],
            ['key' => 'pemakaian_hibah', 'label' => 'Pemakaian Hibah'],
            ['key' => 'modal_akhir_tahun', 'label' => 'Modal Akhir Tahun'],
        ],
    ],
    'arus_kas_masuk' => [
        'title' => 'Laporan Arus Kas Masuk',
        'columns' => [
            ['key' => 'nilai', 'label' => 'Nilai (Rp)', 'field_key' => 'nilai'],
        ],
        'rows' => [
            ['key' => 'saldo_awal', 'label' => 'SALDO AWAL'],
            ['type' => 'group', 'label' => '1. Penerimaan Penempatan Dana pada Bank'],
            ['key' => 'penerimaan_bagi_hasil_bank_syariah', 'label' => '- a. Bagi Hasil Bank Syariah', 'level' => 1],
            ['key' => 'penerimaan_bonus_giro_wadiah', 'label' => '- b. Bonus Giro Wadiah', 'level' => 1],
            ['type' => 'group', 'label' => '2. Penerimaan Pendapatan Margin'],
            ['key' => 'penerimaan_margin_murabahah', 'label' => '- a. Piutang Murabahah', 'level' => 1],
            ['key' => 'penerimaan_margin_salam', 'label' => '- b. Piutang Salam', 'level' => 1],
            ['key' => 'penerimaan_margin_istishna', 'label' => '- c. Piutang Istishna', 'level' => 1],
            ['type' => 'group', 'label' => '3. Penerimaan Pendapatan Bagi Hasil'],
            ['key' => 'penerimaan_bagi_hasil_mudharabah', 'label' => '- a. Mudharabah', 'level' => 1],
            ['key' => 'penerimaan_bagi_hasil_musyarakah', 'label' => '- b. Musyarakah', 'level' => 1],
            ['type' => 'group', 'label' => '4. Pendapatan Sewa dan Multijasa'],
            ['key' => 'penerimaan_sewa_ijaroh', 'label' => '- a. Sewa Ijaroh', 'level' => 1],
            ['key' => 'penerimaan_multijasa', 'label' => '- b. Multijasa', 'level' => 1],
            ['type' => 'group', 'label' => '5. Penerimaan Pendapatan Lainnya'],
            ['key' => 'penerimaan_fee_qardh', 'label' => '- a. Fee Qardh', 'level' => 1],
            ['key' => 'penerimaan_jasa_administrasi', 'label' => '- b. Jasa Administrasi', 'level' => 1],
            ['type' => 'group', 'label' => '6. Penerimaan Piutang'],
            ['key' => 'penerimaan_angsuran_murabahah', 'label' => '- a. Angsuran Murabahah', 'level' => 1],
            ['key' => 'penerimaan_pembayaran_salam', 'label' => '- b. Pembayaran Salam', 'level' => 1],
            ['key' => 'penerimaan_termin_istishna', 'label' => '- c. Termin Istishna', 'level' => 1],
            ['type' => 'group', 'label' => '7. Penerimaan Investasi'],
            ['key' => 'penerimaan_pembayaran_mudharabah', 'label' => '- a. Pembayaran Mudharabah', 'level' => 1],
            ['key' => 'penerimaan_pembayaran_musyarakah', 'label' => '- b. Pembayaran Musyarakah', 'level' => 1],
            ['type' => 'group', 'label' => '8. Penerimaan Multijasa'],
            ['key' => 'penerimaan_angsuran_multijasa', 'label' => '- a. Angsuran Multijasa', 'level' => 1],
            ['type' => 'group', 'label' => '9. Pengembalian Pinjaman'],
            ['key' => 'penerimaan_angsuran_qardh', 'label' => '- a. Angsuran Qardh', 'level' => 1],
            ['key' => 'penerimaan_angsuran_qardhul_hasan', 'label' => '- b. Angsuran Qardhul Hasan', 'level' => 1],
            ['type' => 'group', 'label' => '10. Penerimaan Setoran'],
            ['key' => 'penerimaan_simpanan_sukarela_wadiah', 'label' => '- a. Simpanan Sukarela Wadiah', 'level' => 1, 'auto_key' => 'simpanan_sukarela_inflow'],
            ['key' => 'penerimaan_simpanan_berjangka_mudharabah', 'label' => '- b. Simpanan Sukarela Berjangka Mudharabah', 'level' => 1],
            ['key' => 'penerimaan_pengembalian_investasi_mudharabah_lainnya', 'label' => '- c. Pengembalian Investasi Mudharabah lainnya', 'level' => 1],
            ['key' => 'penerimaan_pengembalian_musyarakah', 'label' => '- d. Pengembalian Musyarakah', 'level' => 1],
            ['key' => 'penerimaan_simpanan_pokok_anggota', 'label' => '- e. Simpanan Pokok Anggota', 'level' => 1, 'auto_key' => 'simpanan_pokok_inflow'],
            ['key' => 'penerimaan_simpanan_wajib_anggota', 'label' => '- f. Simpanan Wajib Anggota', 'level' => 1, 'auto_key' => 'simpanan_wajib_inflow'],
            ['type' => 'group', 'label' => '11. Penerimaan Lainnya'],
            ['key' => 'penerimaan_dana_hibah', 'label' => '- a. Dana Hibah', 'level' => 1],
            ['key' => 'penerimaan_penjualan_aset', 'label' => '- b. Penjualan aset', 'level' => 1],
            ['key' => 'penerimaan_lain_lain', 'label' => '- c. Lain-lain', 'level' => 1],
            [
                'key' => 'jumlah_penerimaan_kas',
                'label' => 'JUMLAH PENERIMAAN KAS',
                'type' => 'total',
                'sum_of' => [
                    'penerimaan_bagi_hasil_bank_syariah',
                    'penerimaan_bonus_giro_wadiah',
                    'penerimaan_margin_murabahah',
                    'penerimaan_margin_salam',
                    'penerimaan_margin_istishna',
                    'penerimaan_bagi_hasil_mudharabah',
                    'penerimaan_bagi_hasil_musyarakah',
                    'penerimaan_sewa_ijaroh',
                    'penerimaan_multijasa',
                    'penerimaan_fee_qardh',
                    'penerimaan_jasa_administrasi',
                    'penerimaan_angsuran_murabahah',
                    'penerimaan_pembayaran_salam',
                    'penerimaan_termin_istishna',
                    'penerimaan_pembayaran_mudharabah',
                    'penerimaan_pembayaran_musyarakah',
                    'penerimaan_angsuran_multijasa',
                    'penerimaan_angsuran_qardh',
                    'penerimaan_angsuran_qardhul_hasan',
                    'penerimaan_simpanan_sukarela_wadiah',
                    'penerimaan_simpanan_berjangka_mudharabah',
                    'penerimaan_pengembalian_investasi_mudharabah_lainnya',
                    'penerimaan_pengembalian_musyarakah',
                    'penerimaan_simpanan_pokok_anggota',
                    'penerimaan_simpanan_wajib_anggota',
                    'penerimaan_dana_hibah',
                    'penerimaan_penjualan_aset',
                    'penerimaan_lain_lain',
                ],
            ],
            [
                'key' => 'jumlah_arus_kas_masuk',
                'label' => 'JUMLAH ARUS KAS MASUK',
                'type' => 'total',
                'sum_of' => [
                    'saldo_awal',
                    'jumlah_penerimaan_kas',
                ],
            ],
        ],
    ],
    'arus_kas_keluar' => [
        'title' => 'Laporan Arus Kas Keluar',
        'columns' => [
            ['key' => 'nilai', 'label' => 'Nilai (Rp)', 'field_key' => 'nilai'],
        ],
        'rows' => [
            ['type' => 'group', 'label' => '12. Penempatan Pada Bank-Bank lain'],
            ['key' => 'penempatan_tabungan_bank_syariah', 'label' => '- a. Tabungan pada Bank Syariah', 'level' => 1],
            ['key' => 'penempatan_giro_bank_syariah', 'label' => '- b. Giro pada Bank Syariah', 'level' => 1],
            ['type' => 'group', 'label' => '13. Penyaluran Piutang'],
            ['key' => 'penyaluran_murabahah', 'label' => '- a. Murabahah', 'level' => 1],
            ['key' => 'penyaluran_salam', 'label' => '- b. Salam', 'level' => 1],
            ['key' => 'penyaluran_istishna', 'label' => '- c. Istishna', 'level' => 1],
            ['type' => 'group', 'label' => '14. Penyaluran Pembiayaan'],
            ['key' => 'penyaluran_mudharabah', 'label' => '- a. Mudharabah', 'level' => 1],
            ['key' => 'penyaluran_musyarakah', 'label' => '- b. Musyarakah', 'level' => 1],
            ['type' => 'group', 'label' => '15. Pemberian Sewa dan Multijasa'],
            ['key' => 'pemberian_sewa_ijaroh', 'label' => '- a. Sewa Ijaroh', 'level' => 1],
            ['key' => 'pemberian_transaksi_multijasa', 'label' => '- b. Transaksi Multijasa', 'level' => 1],
            ['type' => 'group', 'label' => '16. Pemberian Pinjaman'],
            ['key' => 'pemberian_pinjaman_qardh', 'label' => '- a. Pinjaman Qardh', 'level' => 1],
            ['key' => 'pemberian_pinjaman_qardhul_hasan', 'label' => '- b. Pinjaman Qardhul Hasan', 'level' => 1],
            ['type' => 'group', 'label' => '17. Pemberian Imbalan Hasil Pemilik Dana Anggota'],
            ['key' => 'pemberian_bagi_hasil_simpanan_berjangka', 'label' => '- a. Bagi hasil Simpanan Sukarela Berjangka Mudharabah', 'level' => 1],
            ['key' => 'pemberian_bagi_hasil_investasi_mudharabah', 'label' => '- b. Bagi hasil atas Investasi Mudharabah', 'level' => 1],
            ['type' => 'group', 'label' => '18. Pemberian Imbalan Hasil Pemilik Dana Non Anggota'],
            ['key' => 'pemberian_investasi_terikat', 'label' => '- a. Investasi Terikat', 'level' => 1],
            ['key' => 'pemberian_investasi_tidak_terikat', 'label' => '- b. Investasi Tidak Terikat', 'level' => 1],
            ['type' => 'group', 'label' => '19. Pembayaran Beban Operasional'],
            ['key' => 'pembayaran_beban_bonus_simpanan_wadiah', 'label' => '- a. Beban Bonus Simpanan Wadiah', 'level' => 1],
            ['key' => 'pembayaran_beban_tenaga_kerja', 'label' => '- b. Beban tenaga kerja', 'level' => 1],
            ['key' => 'pembayaran_pendidikan_pelatihan', 'label' => '- c. Pendidikan dan Pelatihan', 'level' => 1],
            ['key' => 'pembayaran_promosi', 'label' => '- d. Promosi', 'level' => 1],
            ['key' => 'pembayaran_pajak_pajak', 'label' => '- e. Pajak-Pajak', 'level' => 1],
            ['key' => 'pembayaran_pembelian_aktiva_tetap', 'label' => '- f. Pembelian Aktiva Tetap dan Inventaris', 'level' => 1],
            ['key' => 'pembayaran_penyusutan_amortisasi', 'label' => '- g. Penyusutan Penyisihan / Amortisasi', 'level' => 1],
            ['key' => 'pembayaran_beban_lainnya', 'label' => '- h. Beban Lainnya', 'level' => 1],
            ['type' => 'group', 'label' => '20. Pembayaran kepada Anggota'],
            ['key' => 'pembayaran_penarikan_simpanan_sukarela', 'label' => '- a. Penarikan Simpanan Sukarela Wadiah', 'level' => 1, 'auto_key' => 'simpanan_sukarela_outflow'],
            ['key' => 'pembayaran_pencairan_simpanan_berjangka', 'label' => '- b. Pencairan Simpanan Berjangka Mudharabah', 'level' => 1],
            ['key' => 'pembayaran_pengembalian_investasi_mudharabah', 'label' => '- c. Pengembalian Investasi Mudharabah Lainnya', 'level' => 1],
            ['key' => 'pembayaran_pengembalian_musyarakah', 'label' => '- d. Pengembalian Musyarakah', 'level' => 1],
            ['key' => 'pembayaran_penutupan_simpanan_pokok', 'label' => '- e. Penutupan Simpanan Pokok Anggota', 'level' => 1],
            ['key' => 'pembayaran_penutupan_simpanan_wajib', 'label' => '- f. Penutupan Simpanan Wajib Anggota', 'level' => 1],
            ['type' => 'group', 'label' => '21. Pembayaran Lainnya'],
            ['key' => 'pembayaran_kerugian_force_majeure', 'label' => '- a. Kerugian karena Force majeure', 'level' => 1],
            ['key' => 'pembayaran_lain_lain', 'label' => '- b. Lain-lain', 'level' => 1],
            [
                'key' => 'jumlah_pengeluaran_kas',
                'label' => 'JUMLAH PENGELUARAN KAS',
                'type' => 'total',
                'sum_of' => [
                    'penempatan_tabungan_bank_syariah',
                    'penempatan_giro_bank_syariah',
                    'penyaluran_murabahah',
                    'penyaluran_salam',
                    'penyaluran_istishna',
                    'penyaluran_mudharabah',
                    'penyaluran_musyarakah',
                    'pemberian_sewa_ijaroh',
                    'pemberian_transaksi_multijasa',
                    'pemberian_pinjaman_qardh',
                    'pemberian_pinjaman_qardhul_hasan',
                    'pemberian_bagi_hasil_simpanan_berjangka',
                    'pemberian_bagi_hasil_investasi_mudharabah',
                    'pemberian_investasi_terikat',
                    'pemberian_investasi_tidak_terikat',
                    'pembayaran_beban_bonus_simpanan_wadiah',
                    'pembayaran_beban_tenaga_kerja',
                    'pembayaran_pendidikan_pelatihan',
                    'pembayaran_promosi',
                    'pembayaran_pajak_pajak',
                    'pembayaran_pembelian_aktiva_tetap',
                    'pembayaran_penyusutan_amortisasi',
                    'pembayaran_beban_lainnya',
                    'pembayaran_penarikan_simpanan_sukarela',
                    'pembayaran_pencairan_simpanan_berjangka',
                    'pembayaran_pengembalian_investasi_mudharabah',
                    'pembayaran_pengembalian_musyarakah',
                    'pembayaran_penutupan_simpanan_pokok',
                    'pembayaran_penutupan_simpanan_wajib',
                    'pembayaran_kerugian_force_majeure',
                    'pembayaran_lain_lain',
                ],
            ],
            [
                'key' => 'jumlah_arus_kas_keluar',
                'label' => 'JUMLAH ARUS KAS KELUAR',
                'type' => 'total',
                'sum_of' => [
                    'jumlah_pengeluaran_kas',
                ],
            ],
        ],
    ],
    'rekonsiliasi_bagi_hasil' => [
        'title' => 'Laporan Rekonsiliasi dan Pendapatan Bagi Hasil',
        'columns' => [
            ['key' => 'nilai', 'label' => 'Nilai (Rp)', 'field_key' => 'nilai'],
        ],
        'rows' => [
            ['key' => 'pendapatan_usaha_utama_akrual', 'label' => 'Laporan Pendapatan Usaha Utama (Akrual)'],
            ['type' => 'group', 'label' => 'Pengurang: Pendapatan periode berjalan kas atau setara kas yang masih belum diterima (ditangguhkan)'],
            ['key' => 'pengurang_margin_murabahah', 'label' => '- Margin Murabahah', 'level' => 1],
            ['key' => 'pengurang_margin_istishna', 'label' => '- Margin Istishna', 'level' => 1],
            ['key' => 'pengurang_hak_bagi_hasil_mudharabah', 'label' => '- Hak Bagi hasil : Pembiayaan Mudharabah', 'level' => 1],
            ['key' => 'pengurang_pembiayaan_musyarakah', 'label' => '- Pembiayaan Musyarakah', 'level' => 1],
            ['key' => 'pengurang_pendapatan_sewa', 'label' => '- Pendapatan Sewa', 'level' => 1],
            ['key' => 'jumlah_pengurang', 'label' => 'Jumlah Pengurang', 'type' => 'total'],
            ['type' => 'group', 'label' => 'Penambah: Pendapatan periode sebelumnya yang kasnya Diterima Pada periode berjalan'],
            ['key' => 'penambah_pelunasan_piutang_margin_murabahah', 'label' => '- Penerimaan pelunasan piutang Margin Murabahah', 'level' => 1],
            ['key' => 'penambah_margin_istishna', 'label' => '- Margin Istishna', 'level' => 1],
            ['key' => 'penambah_pendapatan_sewa', 'label' => '- Pendapatan sewa', 'level' => 1],
            ['key' => 'penambah_piutang_bagi_hasil_mudharabah', 'label' => '- Penerimaan Piutang Bagi Hasil Pembiayaan Mudharabah', 'level' => 1],
            ['key' => 'penambah_pembiayaan_musyarakah', 'label' => '- Pembiayaan Musyarakah', 'level' => 1],
            ['key' => 'jumlah_penambah', 'label' => 'Jumlah Penambah', 'type' => 'total'],
            ['key' => 'pendapatan_tersedia_untuk_bagi_hasil', 'label' => 'Pendapatan yang tersedia untuk bagi hasil'],
            ['key' => 'bagi_hasil_hak_koperasi', 'label' => 'Bagi Hasil yang menjadi hak Koperasi Syariah'],
            ['key' => 'bagi_hasil_hak_pemilik_dana', 'label' => 'Bagi Hasil yang menjadi hak pemilik dana'],
            ['key' => 'bagi_hasil_sudah_didistribusikan', 'label' => '- Bagi hasil pemilik dana yang sudah didistribusikan', 'level' => 1],
            ['key' => 'bagi_hasil_belum_didistribusikan', 'label' => '- Bagi hasil pemilik dana yang belum didistribusikan', 'level' => 1],
        ],
    ],
    'dana_zakat' => [
        'title' => 'Laporan Sumber dan Penggunaan Dana Zakat',
        'columns' => [
            ['key' => 'nilai', 'label' => 'Nilai (Rp)', 'field_key' => 'nilai'],
        ],
        'rows' => [
            ['type' => 'group', 'label' => 'Sumber Dana Zakat'],
            ['key' => 'zakat_anggota', 'label' => '- Zakat Anggota Koperasi Syariah', 'level' => 1],
            ['key' => 'zakat_non_anggota', 'label' => '- Zakat Non Anggota Koperasi Syariah', 'level' => 1],
            ['key' => 'jumlah_sumber_dana_zakat', 'label' => 'Jumlah sumber dana zakat', 'type' => 'total'],
            ['type' => 'group', 'label' => 'Penggunaan Dana Zakat'],
            ['key' => 'penggunaan_fakir', 'label' => '- Fakir', 'level' => 1],
            ['key' => 'penggunaan_miskin', 'label' => '- Miskin', 'level' => 1],
            ['key' => 'penggunaan_amil', 'label' => '- Amil', 'level' => 1],
            ['key' => 'penggunaan_mualaf', 'label' => '- Mualaf', 'level' => 1],
            ['key' => 'penggunaan_gharimin', 'label' => '- Gharimin', 'level' => 1],
            ['key' => 'penggunaan_riqab', 'label' => '- Riqab', 'level' => 1],
            ['key' => 'penggunaan_fisabilillah', 'label' => '- Fisabilillah', 'level' => 1],
            ['key' => 'penggunaan_ibnu_sabil', 'label' => '- Ibnu Sabil', 'level' => 1],
            ['key' => 'jumlah_penggunaan_dana_zakat', 'label' => 'Jumlah penggunaan dana Zakat', 'type' => 'total', 'sign' => -1],
            ['key' => 'kenaikan_penurunan_dana_zakat', 'label' => 'Kenaikan (Penurunan Dana Zakat)'],
            ['key' => 'saldo_awal_dana_zakat', 'label' => 'Saldo awal dana zakat'],
            ['key' => 'saldo_akhir_dana_zakat', 'label' => 'Saldo akhir dana zakat'],
        ],
    ],
    'dana_kebajikan' => [
        'title' => 'Laporan Sumber dan Penggunaan Dana Kebajikan',
        'columns' => [
            ['key' => 'nilai', 'label' => 'Nilai (Rp)', 'field_key' => 'nilai'],
        ],
        'rows' => [
            ['type' => 'group', 'label' => 'Sumber Dana Kebajikan'],
            ['key' => 'infak_shadaqoh_anggota', 'label' => '- Infak dan Shadaqoh Anggota Koperasi Syariah', 'level' => 1],
            ['key' => 'infak_shadaqoh_non_anggota', 'label' => '- Infak dan Shadaqoh Non Anggota Koperasi Syariah', 'level' => 1],
            ['key' => 'hasil_pengelolaan_wakaf', 'label' => '- Hasil Pengelolaan Wakaf', 'level' => 1],
            ['key' => 'pengembalian_pinjaman_qardh', 'label' => '- Pengembalian pinjaman Qardh', 'level' => 1],
            ['key' => 'denda_denda', 'label' => '- Denda-denda', 'level' => 1],
            ['key' => 'pendapatan_non_halal', 'label' => '- Pendapatan non halal', 'level' => 1],
            ['key' => 'jumlah_sumber_dana_kebajikan', 'label' => 'Jumlah Sumber Dana Kebajikan', 'type' => 'total'],
            ['type' => 'group', 'label' => 'Penggunaan Dana kebajikan'],
            ['key' => 'penggunaan_pinjaman_qardhul_hasan', 'label' => '- Pinjaman Qardhul Hasan', 'level' => 1],
            ['key' => 'penggunaan_sumbangan', 'label' => '- Sumbangan', 'level' => 1],
            ['key' => 'penggunaan_kepentingan_umum', 'label' => '- Penggunaan untuk kepentingan Umum', 'level' => 1],
            ['key' => 'jumlah_penggunaan_dana_kebajikan', 'label' => 'Jumlah Penggunaan Dana Kebajikan', 'type' => 'total', 'sign' => -1],
            ['key' => 'kenaikan_penurunan_dana_kebajikan', 'label' => 'Kenaikan Penurunan Dana Kebajikan'],
            ['key' => 'saldo_awal_dana_kebajikan', 'label' => 'Saldo awal dana kebajikan'],
            ['key' => 'saldo_akhir_dana_kebajikan', 'label' => 'Saldo akhir dana kebajikan'],
        ],
    ],
];
